export const ARAB_COUNTRY_CODES = [
  { code: "+20", name: "مصر" },
  { code: "+966", name: "السعودية" },
  { code: "+971", name: "الإمارات" },
  { code: "+965", name: "الكويت" },
  { code: "+974", name: "قطر" },
  { code: "+973", name: "البحرين" },
  { code: "+968", name: "عمان" },
  { code: "+962", name: "الأردن" },
  { code: "+961", name: "لبنان" },
  { code: "+963", name: "سوريا" },
  { code: "+964", name: "العراق" },
  { code: "+967", name: "اليمن" },
  { code: "+970", name: "فلسطين" },
  { code: "+212", name: "المغرب" },
  { code: "+213", name: "الجزائر" },
  { code: "+216", name: "تونس" },
  { code: "+218", name: "ليبيا" },
  { code: "+249", name: "السودان" },
  { code: "+222", name: "موريتانيا" },
  { code: "+252", name: "الصومال" },
  { code: "+253", name: "جيبوتي" },
  { code: "+269", name: "جزر القمر" }
];
